### ISSUE TITLE
Hello, Where is bg_snow1.png image file?

### ISSUE THREAD

**Issue by arahansa** [PacktPublishing/Mastering-Android-Game-Development-with-Unity#1]
Hello, Where is bg_snow1.png image file?

**Comment by wajahatkarim3** [comment]
Please find attached the `bg_snow1.png` in this comment.
![bg_snow1](https://user-images.githubusercontent.com/8867121/52958792-a5c92c80-33b6-11e9-9845-ab74aaada73a.png)
