### ISSUE TITLE
bg_snow1.png

### ISSUE THREAD

**Issue by Evgen1919** [PacktPublishing/Mastering-Android-Game-Development-with-Unity#2]
In the files on the github, I did not find the background image bg_snow1.png and bg_snow2.png.  Where they can be downloaded and why is it so disgusting for novice programmers?

**Comment by wajahatkarim3** [comment]
Sorry for the inconveniences. Actually this file was missed while publishing book. You can find it in this issue https://github.com/PacktPublishing/Mastering-Android-Game-Development-with-Unity/issues/1
